# Training configuration
GPU: [0,1,2,3]

VERBOSE: False

SWINUNET:
  IMG_SIZE: 512
  PATCH_SIZE: 2
  WIN_SIZE: 8
  EMB_DIM: 64
  DEPTH_EN: [6, 6, 6, 6]
  HEAD_NUM: [8, 8, 8, 8]
  MLP_RATIO: 4.0
  QKV_BIAS: True
  QK_SCALE: 8
  DROP_RATE: 0.
  ATTN_DROP_RATE: 0.
  DROP_PATH_RATE: 0.1
  APE: False
  PATCH_NORM: True
  USE_CHECKPOINTS: False
  FINAL_UPSAMPLE: 'Dual up-sample'

MODEL:
  MODE: 'Denoising'

# Optimization arguments.
OPTIM:
  BATCH: 1
  EPOCHS: 200
  # EPOCH_DECAY: [10]
  LR_INITIAL: 2e-4
  LR_MIN: 1e-6
  # BETA1: 0.9

TRAINING:
  val: False
  VAL_AFTER_EVERY: 1
  RESUME: False
  TRAIN_PS: 128
  VAL_PS: 512
  TRAIN_DIR: './datasets/train'       # path to training data
  VAL_DIR: './datasets/test' # path to validation data
  SAVE_DIR: './checkpoints/CT/t128v512'           # path to save models and images
